DEBUG 2023-02-15 07:19:24.743 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-02-15 07:19:24.744 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-02-15 07:19:24.744 UTC: 	 Executing command: 'status'
DEBUG 2023-02-15 07:19:24.744 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2023-02-15 07:19:24.745 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCP5_Flat_pythia8 is not a valid CRAB project directory.
ERROR 2023-02-15 07:19:24.745 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCP5_Flat_pythia8 is not a valid CRAB project directory.
INFO 2023-02-15 07:19:24.750 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/JCO_Test/CMSSW_10_6_30/src/Test/QCDEventShape/plugins/crab.log
